scrape_configs:
  - job_name: 'prometheus-local'
    scrape_interval: 1s
    static_configs:
      - targets: ['localhost:9090', 'grafana:3000']

  - job_name: locust
    scrape_interval: 1s
    static_configs:
      - targets: ['locustexporter:4455']

  - job_name: prometheus
    scheme: https
    scrape_interval: 1s
    static_configs:
      - targets: ['prom-1.dj-test.dev.gds-reliability.engineering']
